services:
  scheduler:
    volumes:
      - ./dbt/dw_bootcamp:/usr/local/airflow/dbt/dw_bootcamp

    networks:
      - dw_network

  dag-processor:
    volumes:
      - ./dbt/dw_bootcamp:/usr/local/airflow/dbt/dw_bootcamp

    networks:
      - dw_network

networks:
  dw_network:
    external: true